name: test
on:
  pull_request:
    branches:
      - master # å½“masteråˆ†æ”¯æœ‰å˜æ›´ï¼Œåˆ™æ‰§è¡Œä»¥ä¸‹jobsæ“ä½œ
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Run the Maven test
        run: mvn clean verify;


#  build:
#    name: Hello new contributor
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/first-interaction@v1
#        with:
#          repo-token: ${{ secrets.GITHUB_TOKEN }}
#          issue-message: "Hey, thank you for opening your first Issue ! ğŸ™‚"
#          pr-message: "Hey, thank you for opening your Pull Request !"

#jobs:
#  welcome:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          issue-message: "It's great to have your input on this project."
#          pr-message: "Thank you for contributing to this project, your support is much appreciated."
#          footer: "Stay awesome!"

#jobs:
#  automerge:
#    runs-on: ubuntu-latest
#    steps:
#      - id: automerge
#        name: automerge
#        uses: "pascalgn/automerge-action@v0.15.2"
#        env:
#          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"